/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsUnlimitedResidentialRouteImport } from './routes/docs/unlimited-residential'
import { Route as DocsStaticResidentialRouteImport } from './routes/docs/static-residential'
import { Route as DocsStaticDatacenterRouteImport } from './routes/docs/static-datacenter'
import { Route as DocsResidentialRouteImport } from './routes/docs/residential'
import { Route as DocsMobileRouteImport } from './routes/docs/mobile'
import { Route as DocsIspRouteImport } from './routes/docs/isp'
import { Route as DocsIntroRouteImport } from './routes/docs/intro'
import { Route as DocsFingerprintBrowserRouteImport } from './routes/docs/fingerprint-browser'
import { Route as DocsExtensionRouteImport } from './routes/docs/extension'
import { Route as DocsContactRouteImport } from './routes/docs/contact'
import { Route as DocsChainProxyRouteImport } from './routes/docs/chain-proxy'
import { Route as DocsUnlimitedResidentialQuickstartRouteImport } from './routes/docs/unlimited-residential/quickstart'
import { Route as DocsUnlimitedResidentialIntroRouteImport } from './routes/docs/unlimited-residential/intro'
import { Route as DocsUnlimitedResidentialFirstRequestRouteImport } from './routes/docs/unlimited-residential/first-request'
import { Route as DocsUnlimitedResidentialFaqRouteImport } from './routes/docs/unlimited-residential/faq'
import { Route as DocsUnlimitedResidentialConfigurationRouteImport } from './routes/docs/unlimited-residential/configuration'
import { Route as DocsStaticResidentialQuickstartRouteImport } from './routes/docs/static-residential/quickstart'
import { Route as DocsStaticResidentialIntroRouteImport } from './routes/docs/static-residential/intro'
import { Route as DocsStaticResidentialFirstRequestRouteImport } from './routes/docs/static-residential/first-request'
import { Route as DocsStaticResidentialFaqRouteImport } from './routes/docs/static-residential/faq'
import { Route as DocsStaticResidentialConfigurationRouteImport } from './routes/docs/static-residential/configuration'
import { Route as DocsStaticDatacenterQuickstartRouteImport } from './routes/docs/static-datacenter/quickstart'
import { Route as DocsStaticDatacenterIntroRouteImport } from './routes/docs/static-datacenter/intro'
import { Route as DocsStaticDatacenterFirstRequestRouteImport } from './routes/docs/static-datacenter/first-request'
import { Route as DocsStaticDatacenterFaqRouteImport } from './routes/docs/static-datacenter/faq'
import { Route as DocsStaticDatacenterConfigurationRouteImport } from './routes/docs/static-datacenter/configuration'
import { Route as DocsResidentialQuickstartRouteImport } from './routes/docs/residential/quickstart'
import { Route as DocsResidentialIntroRouteImport } from './routes/docs/residential/intro'
import { Route as DocsResidentialFirstRequestRouteImport } from './routes/docs/residential/first-request'
import { Route as DocsResidentialFaqRouteImport } from './routes/docs/residential/faq'
import { Route as DocsResidentialConfigurationRouteImport } from './routes/docs/residential/configuration'
import { Route as DocsMobileIosRouteImport } from './routes/docs/mobile/ios'
import { Route as DocsMobileAndroidRouteImport } from './routes/docs/mobile/android'
import { Route as DocsIspQuickstartRouteImport } from './routes/docs/isp/quickstart'
import { Route as DocsIspIntroRouteImport } from './routes/docs/isp/intro'
import { Route as DocsIspFirstRequestRouteImport } from './routes/docs/isp/first-request'
import { Route as DocsIspFaqRouteImport } from './routes/docs/isp/faq'
import { Route as DocsIspConfigurationRouteImport } from './routes/docs/isp/configuration'
import { Route as DocsFingerprintBrowserZiniaoRouteImport } from './routes/docs/fingerprint-browser/ziniao'
import { Route as DocsFingerprintBrowserLinkensphereRouteImport } from './routes/docs/fingerprint-browser/linkensphere'
import { Route as DocsFingerprintBrowserIxbrowserRouteImport } from './routes/docs/fingerprint-browser/ixbrowser'
import { Route as DocsFingerprintBrowserHubstudioRouteImport } from './routes/docs/fingerprint-browser/hubstudio'
import { Route as DocsFingerprintBrowserBitbrowserRouteImport } from './routes/docs/fingerprint-browser/bitbrowser'
import { Route as DocsFingerprintBrowserAdspowerRouteImport } from './routes/docs/fingerprint-browser/adspower'
import { Route as DocsFingerprintBrowserVMLoginRouteImport } from './routes/docs/fingerprint-browser/VMLogin'
import { Route as DocsFingerprintBrowserMuLoginRouteImport } from './routes/docs/fingerprint-browser/MuLogin'
import { Route as DocsFingerprintBrowserMoreLoginRouteImport } from './routes/docs/fingerprint-browser/MoreLogin'
import { Route as DocsFingerprintBrowserGoLoginRouteImport } from './routes/docs/fingerprint-browser/GoLogin'
import { Route as DocsExtensionSwitchyOmegaRouteImport } from './routes/docs/extension/SwitchyOmega'
import { Route as DocsExtensionPosternRouteImport } from './routes/docs/extension/Postern'
import { Route as DocsExtensionFoxyProxyRouteImport } from './routes/docs/extension/FoxyProxy'
import { Route as DocsChainProxyV2raynRouteImport } from './routes/docs/chain-proxy/v2rayn'
import { Route as DocsChainProxyProxifierRouteImport } from './routes/docs/chain-proxy/proxifier'
import { Route as DocsChainProxyClashVergeRouteImport } from './routes/docs/chain-proxy/clash-verge'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsUnlimitedResidentialRoute =
  DocsUnlimitedResidentialRouteImport.update({
    id: '/docs/unlimited-residential',
    path: '/docs/unlimited-residential',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsStaticResidentialRoute = DocsStaticResidentialRouteImport.update({
  id: '/docs/static-residential',
  path: '/docs/static-residential',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsStaticDatacenterRoute = DocsStaticDatacenterRouteImport.update({
  id: '/docs/static-datacenter',
  path: '/docs/static-datacenter',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsResidentialRoute = DocsResidentialRouteImport.update({
  id: '/docs/residential',
  path: '/docs/residential',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsMobileRoute = DocsMobileRouteImport.update({
  id: '/docs/mobile',
  path: '/docs/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIspRoute = DocsIspRouteImport.update({
  id: '/docs/isp',
  path: '/docs/isp',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIntroRoute = DocsIntroRouteImport.update({
  id: '/docs/intro',
  path: '/docs/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFingerprintBrowserRoute = DocsFingerprintBrowserRouteImport.update({
  id: '/docs/fingerprint-browser',
  path: '/docs/fingerprint-browser',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsExtensionRoute = DocsExtensionRouteImport.update({
  id: '/docs/extension',
  path: '/docs/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsContactRoute = DocsContactRouteImport.update({
  id: '/docs/contact',
  path: '/docs/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChainProxyRoute = DocsChainProxyRouteImport.update({
  id: '/docs/chain-proxy',
  path: '/docs/chain-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsUnlimitedResidentialQuickstartRoute =
  DocsUnlimitedResidentialQuickstartRouteImport.update({
    id: '/quickstart',
    path: '/quickstart',
    getParentRoute: () => DocsUnlimitedResidentialRoute,
  } as any)
const DocsUnlimitedResidentialIntroRoute =
  DocsUnlimitedResidentialIntroRouteImport.update({
    id: '/intro',
    path: '/intro',
    getParentRoute: () => DocsUnlimitedResidentialRoute,
  } as any)
const DocsUnlimitedResidentialFirstRequestRoute =
  DocsUnlimitedResidentialFirstRequestRouteImport.update({
    id: '/first-request',
    path: '/first-request',
    getParentRoute: () => DocsUnlimitedResidentialRoute,
  } as any)
const DocsUnlimitedResidentialFaqRoute =
  DocsUnlimitedResidentialFaqRouteImport.update({
    id: '/faq',
    path: '/faq',
    getParentRoute: () => DocsUnlimitedResidentialRoute,
  } as any)
const DocsUnlimitedResidentialConfigurationRoute =
  DocsUnlimitedResidentialConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => DocsUnlimitedResidentialRoute,
  } as any)
const DocsStaticResidentialQuickstartRoute =
  DocsStaticResidentialQuickstartRouteImport.update({
    id: '/quickstart',
    path: '/quickstart',
    getParentRoute: () => DocsStaticResidentialRoute,
  } as any)
const DocsStaticResidentialIntroRoute =
  DocsStaticResidentialIntroRouteImport.update({
    id: '/intro',
    path: '/intro',
    getParentRoute: () => DocsStaticResidentialRoute,
  } as any)
const DocsStaticResidentialFirstRequestRoute =
  DocsStaticResidentialFirstRequestRouteImport.update({
    id: '/first-request',
    path: '/first-request',
    getParentRoute: () => DocsStaticResidentialRoute,
  } as any)
const DocsStaticResidentialFaqRoute =
  DocsStaticResidentialFaqRouteImport.update({
    id: '/faq',
    path: '/faq',
    getParentRoute: () => DocsStaticResidentialRoute,
  } as any)
const DocsStaticResidentialConfigurationRoute =
  DocsStaticResidentialConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => DocsStaticResidentialRoute,
  } as any)
const DocsStaticDatacenterQuickstartRoute =
  DocsStaticDatacenterQuickstartRouteImport.update({
    id: '/quickstart',
    path: '/quickstart',
    getParentRoute: () => DocsStaticDatacenterRoute,
  } as any)
const DocsStaticDatacenterIntroRoute =
  DocsStaticDatacenterIntroRouteImport.update({
    id: '/intro',
    path: '/intro',
    getParentRoute: () => DocsStaticDatacenterRoute,
  } as any)
const DocsStaticDatacenterFirstRequestRoute =
  DocsStaticDatacenterFirstRequestRouteImport.update({
    id: '/first-request',
    path: '/first-request',
    getParentRoute: () => DocsStaticDatacenterRoute,
  } as any)
const DocsStaticDatacenterFaqRoute = DocsStaticDatacenterFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsStaticDatacenterRoute,
} as any)
const DocsStaticDatacenterConfigurationRoute =
  DocsStaticDatacenterConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => DocsStaticDatacenterRoute,
  } as any)
const DocsResidentialQuickstartRoute =
  DocsResidentialQuickstartRouteImport.update({
    id: '/quickstart',
    path: '/quickstart',
    getParentRoute: () => DocsResidentialRoute,
  } as any)
const DocsResidentialIntroRoute = DocsResidentialIntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => DocsResidentialRoute,
} as any)
const DocsResidentialFirstRequestRoute =
  DocsResidentialFirstRequestRouteImport.update({
    id: '/first-request',
    path: '/first-request',
    getParentRoute: () => DocsResidentialRoute,
  } as any)
const DocsResidentialFaqRoute = DocsResidentialFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsResidentialRoute,
} as any)
const DocsResidentialConfigurationRoute =
  DocsResidentialConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => DocsResidentialRoute,
  } as any)
const DocsMobileIosRoute = DocsMobileIosRouteImport.update({
  id: '/ios',
  path: '/ios',
  getParentRoute: () => DocsMobileRoute,
} as any)
const DocsMobileAndroidRoute = DocsMobileAndroidRouteImport.update({
  id: '/android',
  path: '/android',
  getParentRoute: () => DocsMobileRoute,
} as any)
const DocsIspQuickstartRoute = DocsIspQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => DocsIspRoute,
} as any)
const DocsIspIntroRoute = DocsIspIntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => DocsIspRoute,
} as any)
const DocsIspFirstRequestRoute = DocsIspFirstRequestRouteImport.update({
  id: '/first-request',
  path: '/first-request',
  getParentRoute: () => DocsIspRoute,
} as any)
const DocsIspFaqRoute = DocsIspFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsIspRoute,
} as any)
const DocsIspConfigurationRoute = DocsIspConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => DocsIspRoute,
} as any)
const DocsFingerprintBrowserZiniaoRoute =
  DocsFingerprintBrowserZiniaoRouteImport.update({
    id: '/ziniao',
    path: '/ziniao',
    getParentRoute: () => DocsFingerprintBrowserRoute,
  } as any)
const DocsFingerprintBrowserLinkensphereRoute =
  DocsFingerprintBrowserLinkensphereRouteImport.update({
    id: '/linkensphere',
    path: '/linkensphere',
    getParentRoute: () => DocsFingerprintBrowserRoute,
  } as any)
const DocsFingerprintBrowserIxbrowserRoute =
  DocsFingerprintBrowserIxbrowserRouteImport.update({
    id: '/ixbrowser',
    path: '/ixbrowser',
    getParentRoute: () => DocsFingerprintBrowserRoute,
  } as any)
const DocsFingerprintBrowserHubstudioRoute =
  DocsFingerprintBrowserHubstudioRouteImport.update({
    id: '/hubstudio',
    path: '/hubstudio',
    getParentRoute: () => DocsFingerprintBrowserRoute,
  } as any)
const DocsFingerprintBrowserBitbrowserRoute =
  DocsFingerprintBrowserBitbrowserRouteImport.update({
    id: '/bitbrowser',
    path: '/bitbrowser',
    getParentRoute: () => DocsFingerprintBrowserRoute,
  } as any)
const DocsFingerprintBrowserAdspowerRoute =
  DocsFingerprintBrowserAdspowerRouteImport.update({
    id: '/adspower',
    path: '/adspower',
    getParentRoute: () => DocsFingerprintBrowserRoute,
  } as any)
const DocsFingerprintBrowserVMLoginRoute =
  DocsFingerprintBrowserVMLoginRouteImport.update({
    id: '/VMLogin',
    path: '/VMLogin',
    getParentRoute: () => DocsFingerprintBrowserRoute,
  } as any)
const DocsFingerprintBrowserMuLoginRoute =
  DocsFingerprintBrowserMuLoginRouteImport.update({
    id: '/MuLogin',
    path: '/MuLogin',
    getParentRoute: () => DocsFingerprintBrowserRoute,
  } as any)
const DocsFingerprintBrowserMoreLoginRoute =
  DocsFingerprintBrowserMoreLoginRouteImport.update({
    id: '/MoreLogin',
    path: '/MoreLogin',
    getParentRoute: () => DocsFingerprintBrowserRoute,
  } as any)
const DocsFingerprintBrowserGoLoginRoute =
  DocsFingerprintBrowserGoLoginRouteImport.update({
    id: '/GoLogin',
    path: '/GoLogin',
    getParentRoute: () => DocsFingerprintBrowserRoute,
  } as any)
const DocsExtensionSwitchyOmegaRoute =
  DocsExtensionSwitchyOmegaRouteImport.update({
    id: '/SwitchyOmega',
    path: '/SwitchyOmega',
    getParentRoute: () => DocsExtensionRoute,
  } as any)
const DocsExtensionPosternRoute = DocsExtensionPosternRouteImport.update({
  id: '/Postern',
  path: '/Postern',
  getParentRoute: () => DocsExtensionRoute,
} as any)
const DocsExtensionFoxyProxyRoute = DocsExtensionFoxyProxyRouteImport.update({
  id: '/FoxyProxy',
  path: '/FoxyProxy',
  getParentRoute: () => DocsExtensionRoute,
} as any)
const DocsChainProxyV2raynRoute = DocsChainProxyV2raynRouteImport.update({
  id: '/v2rayn',
  path: '/v2rayn',
  getParentRoute: () => DocsChainProxyRoute,
} as any)
const DocsChainProxyProxifierRoute = DocsChainProxyProxifierRouteImport.update({
  id: '/proxifier',
  path: '/proxifier',
  getParentRoute: () => DocsChainProxyRoute,
} as any)
const DocsChainProxyClashVergeRoute =
  DocsChainProxyClashVergeRouteImport.update({
    id: '/clash-verge',
    path: '/clash-verge',
    getParentRoute: () => DocsChainProxyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/chain-proxy': typeof DocsChainProxyRouteWithChildren
  '/docs/contact': typeof DocsContactRoute
  '/docs/extension': typeof DocsExtensionRouteWithChildren
  '/docs/fingerprint-browser': typeof DocsFingerprintBrowserRouteWithChildren
  '/docs/intro': typeof DocsIntroRoute
  '/docs/isp': typeof DocsIspRouteWithChildren
  '/docs/mobile': typeof DocsMobileRouteWithChildren
  '/docs/residential': typeof DocsResidentialRouteWithChildren
  '/docs/static-datacenter': typeof DocsStaticDatacenterRouteWithChildren
  '/docs/static-residential': typeof DocsStaticResidentialRouteWithChildren
  '/docs/unlimited-residential': typeof DocsUnlimitedResidentialRouteWithChildren
  '/docs/chain-proxy/clash-verge': typeof DocsChainProxyClashVergeRoute
  '/docs/chain-proxy/proxifier': typeof DocsChainProxyProxifierRoute
  '/docs/chain-proxy/v2rayn': typeof DocsChainProxyV2raynRoute
  '/docs/extension/FoxyProxy': typeof DocsExtensionFoxyProxyRoute
  '/docs/extension/Postern': typeof DocsExtensionPosternRoute
  '/docs/extension/SwitchyOmega': typeof DocsExtensionSwitchyOmegaRoute
  '/docs/fingerprint-browser/GoLogin': typeof DocsFingerprintBrowserGoLoginRoute
  '/docs/fingerprint-browser/MoreLogin': typeof DocsFingerprintBrowserMoreLoginRoute
  '/docs/fingerprint-browser/MuLogin': typeof DocsFingerprintBrowserMuLoginRoute
  '/docs/fingerprint-browser/VMLogin': typeof DocsFingerprintBrowserVMLoginRoute
  '/docs/fingerprint-browser/adspower': typeof DocsFingerprintBrowserAdspowerRoute
  '/docs/fingerprint-browser/bitbrowser': typeof DocsFingerprintBrowserBitbrowserRoute
  '/docs/fingerprint-browser/hubstudio': typeof DocsFingerprintBrowserHubstudioRoute
  '/docs/fingerprint-browser/ixbrowser': typeof DocsFingerprintBrowserIxbrowserRoute
  '/docs/fingerprint-browser/linkensphere': typeof DocsFingerprintBrowserLinkensphereRoute
  '/docs/fingerprint-browser/ziniao': typeof DocsFingerprintBrowserZiniaoRoute
  '/docs/isp/configuration': typeof DocsIspConfigurationRoute
  '/docs/isp/faq': typeof DocsIspFaqRoute
  '/docs/isp/first-request': typeof DocsIspFirstRequestRoute
  '/docs/isp/intro': typeof DocsIspIntroRoute
  '/docs/isp/quickstart': typeof DocsIspQuickstartRoute
  '/docs/mobile/android': typeof DocsMobileAndroidRoute
  '/docs/mobile/ios': typeof DocsMobileIosRoute
  '/docs/residential/configuration': typeof DocsResidentialConfigurationRoute
  '/docs/residential/faq': typeof DocsResidentialFaqRoute
  '/docs/residential/first-request': typeof DocsResidentialFirstRequestRoute
  '/docs/residential/intro': typeof DocsResidentialIntroRoute
  '/docs/residential/quickstart': typeof DocsResidentialQuickstartRoute
  '/docs/static-datacenter/configuration': typeof DocsStaticDatacenterConfigurationRoute
  '/docs/static-datacenter/faq': typeof DocsStaticDatacenterFaqRoute
  '/docs/static-datacenter/first-request': typeof DocsStaticDatacenterFirstRequestRoute
  '/docs/static-datacenter/intro': typeof DocsStaticDatacenterIntroRoute
  '/docs/static-datacenter/quickstart': typeof DocsStaticDatacenterQuickstartRoute
  '/docs/static-residential/configuration': typeof DocsStaticResidentialConfigurationRoute
  '/docs/static-residential/faq': typeof DocsStaticResidentialFaqRoute
  '/docs/static-residential/first-request': typeof DocsStaticResidentialFirstRequestRoute
  '/docs/static-residential/intro': typeof DocsStaticResidentialIntroRoute
  '/docs/static-residential/quickstart': typeof DocsStaticResidentialQuickstartRoute
  '/docs/unlimited-residential/configuration': typeof DocsUnlimitedResidentialConfigurationRoute
  '/docs/unlimited-residential/faq': typeof DocsUnlimitedResidentialFaqRoute
  '/docs/unlimited-residential/first-request': typeof DocsUnlimitedResidentialFirstRequestRoute
  '/docs/unlimited-residential/intro': typeof DocsUnlimitedResidentialIntroRoute
  '/docs/unlimited-residential/quickstart': typeof DocsUnlimitedResidentialQuickstartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/chain-proxy': typeof DocsChainProxyRouteWithChildren
  '/docs/contact': typeof DocsContactRoute
  '/docs/extension': typeof DocsExtensionRouteWithChildren
  '/docs/fingerprint-browser': typeof DocsFingerprintBrowserRouteWithChildren
  '/docs/intro': typeof DocsIntroRoute
  '/docs/isp': typeof DocsIspRouteWithChildren
  '/docs/mobile': typeof DocsMobileRouteWithChildren
  '/docs/residential': typeof DocsResidentialRouteWithChildren
  '/docs/static-datacenter': typeof DocsStaticDatacenterRouteWithChildren
  '/docs/static-residential': typeof DocsStaticResidentialRouteWithChildren
  '/docs/unlimited-residential': typeof DocsUnlimitedResidentialRouteWithChildren
  '/docs/chain-proxy/clash-verge': typeof DocsChainProxyClashVergeRoute
  '/docs/chain-proxy/proxifier': typeof DocsChainProxyProxifierRoute
  '/docs/chain-proxy/v2rayn': typeof DocsChainProxyV2raynRoute
  '/docs/extension/FoxyProxy': typeof DocsExtensionFoxyProxyRoute
  '/docs/extension/Postern': typeof DocsExtensionPosternRoute
  '/docs/extension/SwitchyOmega': typeof DocsExtensionSwitchyOmegaRoute
  '/docs/fingerprint-browser/GoLogin': typeof DocsFingerprintBrowserGoLoginRoute
  '/docs/fingerprint-browser/MoreLogin': typeof DocsFingerprintBrowserMoreLoginRoute
  '/docs/fingerprint-browser/MuLogin': typeof DocsFingerprintBrowserMuLoginRoute
  '/docs/fingerprint-browser/VMLogin': typeof DocsFingerprintBrowserVMLoginRoute
  '/docs/fingerprint-browser/adspower': typeof DocsFingerprintBrowserAdspowerRoute
  '/docs/fingerprint-browser/bitbrowser': typeof DocsFingerprintBrowserBitbrowserRoute
  '/docs/fingerprint-browser/hubstudio': typeof DocsFingerprintBrowserHubstudioRoute
  '/docs/fingerprint-browser/ixbrowser': typeof DocsFingerprintBrowserIxbrowserRoute
  '/docs/fingerprint-browser/linkensphere': typeof DocsFingerprintBrowserLinkensphereRoute
  '/docs/fingerprint-browser/ziniao': typeof DocsFingerprintBrowserZiniaoRoute
  '/docs/isp/configuration': typeof DocsIspConfigurationRoute
  '/docs/isp/faq': typeof DocsIspFaqRoute
  '/docs/isp/first-request': typeof DocsIspFirstRequestRoute
  '/docs/isp/intro': typeof DocsIspIntroRoute
  '/docs/isp/quickstart': typeof DocsIspQuickstartRoute
  '/docs/mobile/android': typeof DocsMobileAndroidRoute
  '/docs/mobile/ios': typeof DocsMobileIosRoute
  '/docs/residential/configuration': typeof DocsResidentialConfigurationRoute
  '/docs/residential/faq': typeof DocsResidentialFaqRoute
  '/docs/residential/first-request': typeof DocsResidentialFirstRequestRoute
  '/docs/residential/intro': typeof DocsResidentialIntroRoute
  '/docs/residential/quickstart': typeof DocsResidentialQuickstartRoute
  '/docs/static-datacenter/configuration': typeof DocsStaticDatacenterConfigurationRoute
  '/docs/static-datacenter/faq': typeof DocsStaticDatacenterFaqRoute
  '/docs/static-datacenter/first-request': typeof DocsStaticDatacenterFirstRequestRoute
  '/docs/static-datacenter/intro': typeof DocsStaticDatacenterIntroRoute
  '/docs/static-datacenter/quickstart': typeof DocsStaticDatacenterQuickstartRoute
  '/docs/static-residential/configuration': typeof DocsStaticResidentialConfigurationRoute
  '/docs/static-residential/faq': typeof DocsStaticResidentialFaqRoute
  '/docs/static-residential/first-request': typeof DocsStaticResidentialFirstRequestRoute
  '/docs/static-residential/intro': typeof DocsStaticResidentialIntroRoute
  '/docs/static-residential/quickstart': typeof DocsStaticResidentialQuickstartRoute
  '/docs/unlimited-residential/configuration': typeof DocsUnlimitedResidentialConfigurationRoute
  '/docs/unlimited-residential/faq': typeof DocsUnlimitedResidentialFaqRoute
  '/docs/unlimited-residential/first-request': typeof DocsUnlimitedResidentialFirstRequestRoute
  '/docs/unlimited-residential/intro': typeof DocsUnlimitedResidentialIntroRoute
  '/docs/unlimited-residential/quickstart': typeof DocsUnlimitedResidentialQuickstartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/chain-proxy': typeof DocsChainProxyRouteWithChildren
  '/docs/contact': typeof DocsContactRoute
  '/docs/extension': typeof DocsExtensionRouteWithChildren
  '/docs/fingerprint-browser': typeof DocsFingerprintBrowserRouteWithChildren
  '/docs/intro': typeof DocsIntroRoute
  '/docs/isp': typeof DocsIspRouteWithChildren
  '/docs/mobile': typeof DocsMobileRouteWithChildren
  '/docs/residential': typeof DocsResidentialRouteWithChildren
  '/docs/static-datacenter': typeof DocsStaticDatacenterRouteWithChildren
  '/docs/static-residential': typeof DocsStaticResidentialRouteWithChildren
  '/docs/unlimited-residential': typeof DocsUnlimitedResidentialRouteWithChildren
  '/docs/chain-proxy/clash-verge': typeof DocsChainProxyClashVergeRoute
  '/docs/chain-proxy/proxifier': typeof DocsChainProxyProxifierRoute
  '/docs/chain-proxy/v2rayn': typeof DocsChainProxyV2raynRoute
  '/docs/extension/FoxyProxy': typeof DocsExtensionFoxyProxyRoute
  '/docs/extension/Postern': typeof DocsExtensionPosternRoute
  '/docs/extension/SwitchyOmega': typeof DocsExtensionSwitchyOmegaRoute
  '/docs/fingerprint-browser/GoLogin': typeof DocsFingerprintBrowserGoLoginRoute
  '/docs/fingerprint-browser/MoreLogin': typeof DocsFingerprintBrowserMoreLoginRoute
  '/docs/fingerprint-browser/MuLogin': typeof DocsFingerprintBrowserMuLoginRoute
  '/docs/fingerprint-browser/VMLogin': typeof DocsFingerprintBrowserVMLoginRoute
  '/docs/fingerprint-browser/adspower': typeof DocsFingerprintBrowserAdspowerRoute
  '/docs/fingerprint-browser/bitbrowser': typeof DocsFingerprintBrowserBitbrowserRoute
  '/docs/fingerprint-browser/hubstudio': typeof DocsFingerprintBrowserHubstudioRoute
  '/docs/fingerprint-browser/ixbrowser': typeof DocsFingerprintBrowserIxbrowserRoute
  '/docs/fingerprint-browser/linkensphere': typeof DocsFingerprintBrowserLinkensphereRoute
  '/docs/fingerprint-browser/ziniao': typeof DocsFingerprintBrowserZiniaoRoute
  '/docs/isp/configuration': typeof DocsIspConfigurationRoute
  '/docs/isp/faq': typeof DocsIspFaqRoute
  '/docs/isp/first-request': typeof DocsIspFirstRequestRoute
  '/docs/isp/intro': typeof DocsIspIntroRoute
  '/docs/isp/quickstart': typeof DocsIspQuickstartRoute
  '/docs/mobile/android': typeof DocsMobileAndroidRoute
  '/docs/mobile/ios': typeof DocsMobileIosRoute
  '/docs/residential/configuration': typeof DocsResidentialConfigurationRoute
  '/docs/residential/faq': typeof DocsResidentialFaqRoute
  '/docs/residential/first-request': typeof DocsResidentialFirstRequestRoute
  '/docs/residential/intro': typeof DocsResidentialIntroRoute
  '/docs/residential/quickstart': typeof DocsResidentialQuickstartRoute
  '/docs/static-datacenter/configuration': typeof DocsStaticDatacenterConfigurationRoute
  '/docs/static-datacenter/faq': typeof DocsStaticDatacenterFaqRoute
  '/docs/static-datacenter/first-request': typeof DocsStaticDatacenterFirstRequestRoute
  '/docs/static-datacenter/intro': typeof DocsStaticDatacenterIntroRoute
  '/docs/static-datacenter/quickstart': typeof DocsStaticDatacenterQuickstartRoute
  '/docs/static-residential/configuration': typeof DocsStaticResidentialConfigurationRoute
  '/docs/static-residential/faq': typeof DocsStaticResidentialFaqRoute
  '/docs/static-residential/first-request': typeof DocsStaticResidentialFirstRequestRoute
  '/docs/static-residential/intro': typeof DocsStaticResidentialIntroRoute
  '/docs/static-residential/quickstart': typeof DocsStaticResidentialQuickstartRoute
  '/docs/unlimited-residential/configuration': typeof DocsUnlimitedResidentialConfigurationRoute
  '/docs/unlimited-residential/faq': typeof DocsUnlimitedResidentialFaqRoute
  '/docs/unlimited-residential/first-request': typeof DocsUnlimitedResidentialFirstRequestRoute
  '/docs/unlimited-residential/intro': typeof DocsUnlimitedResidentialIntroRoute
  '/docs/unlimited-residential/quickstart': typeof DocsUnlimitedResidentialQuickstartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs/chain-proxy'
    | '/docs/contact'
    | '/docs/extension'
    | '/docs/fingerprint-browser'
    | '/docs/intro'
    | '/docs/isp'
    | '/docs/mobile'
    | '/docs/residential'
    | '/docs/static-datacenter'
    | '/docs/static-residential'
    | '/docs/unlimited-residential'
    | '/docs/chain-proxy/clash-verge'
    | '/docs/chain-proxy/proxifier'
    | '/docs/chain-proxy/v2rayn'
    | '/docs/extension/FoxyProxy'
    | '/docs/extension/Postern'
    | '/docs/extension/SwitchyOmega'
    | '/docs/fingerprint-browser/GoLogin'
    | '/docs/fingerprint-browser/MoreLogin'
    | '/docs/fingerprint-browser/MuLogin'
    | '/docs/fingerprint-browser/VMLogin'
    | '/docs/fingerprint-browser/adspower'
    | '/docs/fingerprint-browser/bitbrowser'
    | '/docs/fingerprint-browser/hubstudio'
    | '/docs/fingerprint-browser/ixbrowser'
    | '/docs/fingerprint-browser/linkensphere'
    | '/docs/fingerprint-browser/ziniao'
    | '/docs/isp/configuration'
    | '/docs/isp/faq'
    | '/docs/isp/first-request'
    | '/docs/isp/intro'
    | '/docs/isp/quickstart'
    | '/docs/mobile/android'
    | '/docs/mobile/ios'
    | '/docs/residential/configuration'
    | '/docs/residential/faq'
    | '/docs/residential/first-request'
    | '/docs/residential/intro'
    | '/docs/residential/quickstart'
    | '/docs/static-datacenter/configuration'
    | '/docs/static-datacenter/faq'
    | '/docs/static-datacenter/first-request'
    | '/docs/static-datacenter/intro'
    | '/docs/static-datacenter/quickstart'
    | '/docs/static-residential/configuration'
    | '/docs/static-residential/faq'
    | '/docs/static-residential/first-request'
    | '/docs/static-residential/intro'
    | '/docs/static-residential/quickstart'
    | '/docs/unlimited-residential/configuration'
    | '/docs/unlimited-residential/faq'
    | '/docs/unlimited-residential/first-request'
    | '/docs/unlimited-residential/intro'
    | '/docs/unlimited-residential/quickstart'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/chain-proxy'
    | '/docs/contact'
    | '/docs/extension'
    | '/docs/fingerprint-browser'
    | '/docs/intro'
    | '/docs/isp'
    | '/docs/mobile'
    | '/docs/residential'
    | '/docs/static-datacenter'
    | '/docs/static-residential'
    | '/docs/unlimited-residential'
    | '/docs/chain-proxy/clash-verge'
    | '/docs/chain-proxy/proxifier'
    | '/docs/chain-proxy/v2rayn'
    | '/docs/extension/FoxyProxy'
    | '/docs/extension/Postern'
    | '/docs/extension/SwitchyOmega'
    | '/docs/fingerprint-browser/GoLogin'
    | '/docs/fingerprint-browser/MoreLogin'
    | '/docs/fingerprint-browser/MuLogin'
    | '/docs/fingerprint-browser/VMLogin'
    | '/docs/fingerprint-browser/adspower'
    | '/docs/fingerprint-browser/bitbrowser'
    | '/docs/fingerprint-browser/hubstudio'
    | '/docs/fingerprint-browser/ixbrowser'
    | '/docs/fingerprint-browser/linkensphere'
    | '/docs/fingerprint-browser/ziniao'
    | '/docs/isp/configuration'
    | '/docs/isp/faq'
    | '/docs/isp/first-request'
    | '/docs/isp/intro'
    | '/docs/isp/quickstart'
    | '/docs/mobile/android'
    | '/docs/mobile/ios'
    | '/docs/residential/configuration'
    | '/docs/residential/faq'
    | '/docs/residential/first-request'
    | '/docs/residential/intro'
    | '/docs/residential/quickstart'
    | '/docs/static-datacenter/configuration'
    | '/docs/static-datacenter/faq'
    | '/docs/static-datacenter/first-request'
    | '/docs/static-datacenter/intro'
    | '/docs/static-datacenter/quickstart'
    | '/docs/static-residential/configuration'
    | '/docs/static-residential/faq'
    | '/docs/static-residential/first-request'
    | '/docs/static-residential/intro'
    | '/docs/static-residential/quickstart'
    | '/docs/unlimited-residential/configuration'
    | '/docs/unlimited-residential/faq'
    | '/docs/unlimited-residential/first-request'
    | '/docs/unlimited-residential/intro'
    | '/docs/unlimited-residential/quickstart'
  id:
    | '__root__'
    | '/'
    | '/docs/chain-proxy'
    | '/docs/contact'
    | '/docs/extension'
    | '/docs/fingerprint-browser'
    | '/docs/intro'
    | '/docs/isp'
    | '/docs/mobile'
    | '/docs/residential'
    | '/docs/static-datacenter'
    | '/docs/static-residential'
    | '/docs/unlimited-residential'
    | '/docs/chain-proxy/clash-verge'
    | '/docs/chain-proxy/proxifier'
    | '/docs/chain-proxy/v2rayn'
    | '/docs/extension/FoxyProxy'
    | '/docs/extension/Postern'
    | '/docs/extension/SwitchyOmega'
    | '/docs/fingerprint-browser/GoLogin'
    | '/docs/fingerprint-browser/MoreLogin'
    | '/docs/fingerprint-browser/MuLogin'
    | '/docs/fingerprint-browser/VMLogin'
    | '/docs/fingerprint-browser/adspower'
    | '/docs/fingerprint-browser/bitbrowser'
    | '/docs/fingerprint-browser/hubstudio'
    | '/docs/fingerprint-browser/ixbrowser'
    | '/docs/fingerprint-browser/linkensphere'
    | '/docs/fingerprint-browser/ziniao'
    | '/docs/isp/configuration'
    | '/docs/isp/faq'
    | '/docs/isp/first-request'
    | '/docs/isp/intro'
    | '/docs/isp/quickstart'
    | '/docs/mobile/android'
    | '/docs/mobile/ios'
    | '/docs/residential/configuration'
    | '/docs/residential/faq'
    | '/docs/residential/first-request'
    | '/docs/residential/intro'
    | '/docs/residential/quickstart'
    | '/docs/static-datacenter/configuration'
    | '/docs/static-datacenter/faq'
    | '/docs/static-datacenter/first-request'
    | '/docs/static-datacenter/intro'
    | '/docs/static-datacenter/quickstart'
    | '/docs/static-residential/configuration'
    | '/docs/static-residential/faq'
    | '/docs/static-residential/first-request'
    | '/docs/static-residential/intro'
    | '/docs/static-residential/quickstart'
    | '/docs/unlimited-residential/configuration'
    | '/docs/unlimited-residential/faq'
    | '/docs/unlimited-residential/first-request'
    | '/docs/unlimited-residential/intro'
    | '/docs/unlimited-residential/quickstart'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsChainProxyRoute: typeof DocsChainProxyRouteWithChildren
  DocsContactRoute: typeof DocsContactRoute
  DocsExtensionRoute: typeof DocsExtensionRouteWithChildren
  DocsFingerprintBrowserRoute: typeof DocsFingerprintBrowserRouteWithChildren
  DocsIntroRoute: typeof DocsIntroRoute
  DocsIspRoute: typeof DocsIspRouteWithChildren
  DocsMobileRoute: typeof DocsMobileRouteWithChildren
  DocsResidentialRoute: typeof DocsResidentialRouteWithChildren
  DocsStaticDatacenterRoute: typeof DocsStaticDatacenterRouteWithChildren
  DocsStaticResidentialRoute: typeof DocsStaticResidentialRouteWithChildren
  DocsUnlimitedResidentialRoute: typeof DocsUnlimitedResidentialRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/unlimited-residential': {
      id: '/docs/unlimited-residential'
      path: '/docs/unlimited-residential'
      fullPath: '/docs/unlimited-residential'
      preLoaderRoute: typeof DocsUnlimitedResidentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/static-residential': {
      id: '/docs/static-residential'
      path: '/docs/static-residential'
      fullPath: '/docs/static-residential'
      preLoaderRoute: typeof DocsStaticResidentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/static-datacenter': {
      id: '/docs/static-datacenter'
      path: '/docs/static-datacenter'
      fullPath: '/docs/static-datacenter'
      preLoaderRoute: typeof DocsStaticDatacenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/residential': {
      id: '/docs/residential'
      path: '/docs/residential'
      fullPath: '/docs/residential'
      preLoaderRoute: typeof DocsResidentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/mobile': {
      id: '/docs/mobile'
      path: '/docs/mobile'
      fullPath: '/docs/mobile'
      preLoaderRoute: typeof DocsMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/isp': {
      id: '/docs/isp'
      path: '/docs/isp'
      fullPath: '/docs/isp'
      preLoaderRoute: typeof DocsIspRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/intro': {
      id: '/docs/intro'
      path: '/docs/intro'
      fullPath: '/docs/intro'
      preLoaderRoute: typeof DocsIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/fingerprint-browser': {
      id: '/docs/fingerprint-browser'
      path: '/docs/fingerprint-browser'
      fullPath: '/docs/fingerprint-browser'
      preLoaderRoute: typeof DocsFingerprintBrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/extension': {
      id: '/docs/extension'
      path: '/docs/extension'
      fullPath: '/docs/extension'
      preLoaderRoute: typeof DocsExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/contact': {
      id: '/docs/contact'
      path: '/docs/contact'
      fullPath: '/docs/contact'
      preLoaderRoute: typeof DocsContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/chain-proxy': {
      id: '/docs/chain-proxy'
      path: '/docs/chain-proxy'
      fullPath: '/docs/chain-proxy'
      preLoaderRoute: typeof DocsChainProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/unlimited-residential/quickstart': {
      id: '/docs/unlimited-residential/quickstart'
      path: '/quickstart'
      fullPath: '/docs/unlimited-residential/quickstart'
      preLoaderRoute: typeof DocsUnlimitedResidentialQuickstartRouteImport
      parentRoute: typeof DocsUnlimitedResidentialRoute
    }
    '/docs/unlimited-residential/intro': {
      id: '/docs/unlimited-residential/intro'
      path: '/intro'
      fullPath: '/docs/unlimited-residential/intro'
      preLoaderRoute: typeof DocsUnlimitedResidentialIntroRouteImport
      parentRoute: typeof DocsUnlimitedResidentialRoute
    }
    '/docs/unlimited-residential/first-request': {
      id: '/docs/unlimited-residential/first-request'
      path: '/first-request'
      fullPath: '/docs/unlimited-residential/first-request'
      preLoaderRoute: typeof DocsUnlimitedResidentialFirstRequestRouteImport
      parentRoute: typeof DocsUnlimitedResidentialRoute
    }
    '/docs/unlimited-residential/faq': {
      id: '/docs/unlimited-residential/faq'
      path: '/faq'
      fullPath: '/docs/unlimited-residential/faq'
      preLoaderRoute: typeof DocsUnlimitedResidentialFaqRouteImport
      parentRoute: typeof DocsUnlimitedResidentialRoute
    }
    '/docs/unlimited-residential/configuration': {
      id: '/docs/unlimited-residential/configuration'
      path: '/configuration'
      fullPath: '/docs/unlimited-residential/configuration'
      preLoaderRoute: typeof DocsUnlimitedResidentialConfigurationRouteImport
      parentRoute: typeof DocsUnlimitedResidentialRoute
    }
    '/docs/static-residential/quickstart': {
      id: '/docs/static-residential/quickstart'
      path: '/quickstart'
      fullPath: '/docs/static-residential/quickstart'
      preLoaderRoute: typeof DocsStaticResidentialQuickstartRouteImport
      parentRoute: typeof DocsStaticResidentialRoute
    }
    '/docs/static-residential/intro': {
      id: '/docs/static-residential/intro'
      path: '/intro'
      fullPath: '/docs/static-residential/intro'
      preLoaderRoute: typeof DocsStaticResidentialIntroRouteImport
      parentRoute: typeof DocsStaticResidentialRoute
    }
    '/docs/static-residential/first-request': {
      id: '/docs/static-residential/first-request'
      path: '/first-request'
      fullPath: '/docs/static-residential/first-request'
      preLoaderRoute: typeof DocsStaticResidentialFirstRequestRouteImport
      parentRoute: typeof DocsStaticResidentialRoute
    }
    '/docs/static-residential/faq': {
      id: '/docs/static-residential/faq'
      path: '/faq'
      fullPath: '/docs/static-residential/faq'
      preLoaderRoute: typeof DocsStaticResidentialFaqRouteImport
      parentRoute: typeof DocsStaticResidentialRoute
    }
    '/docs/static-residential/configuration': {
      id: '/docs/static-residential/configuration'
      path: '/configuration'
      fullPath: '/docs/static-residential/configuration'
      preLoaderRoute: typeof DocsStaticResidentialConfigurationRouteImport
      parentRoute: typeof DocsStaticResidentialRoute
    }
    '/docs/static-datacenter/quickstart': {
      id: '/docs/static-datacenter/quickstart'
      path: '/quickstart'
      fullPath: '/docs/static-datacenter/quickstart'
      preLoaderRoute: typeof DocsStaticDatacenterQuickstartRouteImport
      parentRoute: typeof DocsStaticDatacenterRoute
    }
    '/docs/static-datacenter/intro': {
      id: '/docs/static-datacenter/intro'
      path: '/intro'
      fullPath: '/docs/static-datacenter/intro'
      preLoaderRoute: typeof DocsStaticDatacenterIntroRouteImport
      parentRoute: typeof DocsStaticDatacenterRoute
    }
    '/docs/static-datacenter/first-request': {
      id: '/docs/static-datacenter/first-request'
      path: '/first-request'
      fullPath: '/docs/static-datacenter/first-request'
      preLoaderRoute: typeof DocsStaticDatacenterFirstRequestRouteImport
      parentRoute: typeof DocsStaticDatacenterRoute
    }
    '/docs/static-datacenter/faq': {
      id: '/docs/static-datacenter/faq'
      path: '/faq'
      fullPath: '/docs/static-datacenter/faq'
      preLoaderRoute: typeof DocsStaticDatacenterFaqRouteImport
      parentRoute: typeof DocsStaticDatacenterRoute
    }
    '/docs/static-datacenter/configuration': {
      id: '/docs/static-datacenter/configuration'
      path: '/configuration'
      fullPath: '/docs/static-datacenter/configuration'
      preLoaderRoute: typeof DocsStaticDatacenterConfigurationRouteImport
      parentRoute: typeof DocsStaticDatacenterRoute
    }
    '/docs/residential/quickstart': {
      id: '/docs/residential/quickstart'
      path: '/quickstart'
      fullPath: '/docs/residential/quickstart'
      preLoaderRoute: typeof DocsResidentialQuickstartRouteImport
      parentRoute: typeof DocsResidentialRoute
    }
    '/docs/residential/intro': {
      id: '/docs/residential/intro'
      path: '/intro'
      fullPath: '/docs/residential/intro'
      preLoaderRoute: typeof DocsResidentialIntroRouteImport
      parentRoute: typeof DocsResidentialRoute
    }
    '/docs/residential/first-request': {
      id: '/docs/residential/first-request'
      path: '/first-request'
      fullPath: '/docs/residential/first-request'
      preLoaderRoute: typeof DocsResidentialFirstRequestRouteImport
      parentRoute: typeof DocsResidentialRoute
    }
    '/docs/residential/faq': {
      id: '/docs/residential/faq'
      path: '/faq'
      fullPath: '/docs/residential/faq'
      preLoaderRoute: typeof DocsResidentialFaqRouteImport
      parentRoute: typeof DocsResidentialRoute
    }
    '/docs/residential/configuration': {
      id: '/docs/residential/configuration'
      path: '/configuration'
      fullPath: '/docs/residential/configuration'
      preLoaderRoute: typeof DocsResidentialConfigurationRouteImport
      parentRoute: typeof DocsResidentialRoute
    }
    '/docs/mobile/ios': {
      id: '/docs/mobile/ios'
      path: '/ios'
      fullPath: '/docs/mobile/ios'
      preLoaderRoute: typeof DocsMobileIosRouteImport
      parentRoute: typeof DocsMobileRoute
    }
    '/docs/mobile/android': {
      id: '/docs/mobile/android'
      path: '/android'
      fullPath: '/docs/mobile/android'
      preLoaderRoute: typeof DocsMobileAndroidRouteImport
      parentRoute: typeof DocsMobileRoute
    }
    '/docs/isp/quickstart': {
      id: '/docs/isp/quickstart'
      path: '/quickstart'
      fullPath: '/docs/isp/quickstart'
      preLoaderRoute: typeof DocsIspQuickstartRouteImport
      parentRoute: typeof DocsIspRoute
    }
    '/docs/isp/intro': {
      id: '/docs/isp/intro'
      path: '/intro'
      fullPath: '/docs/isp/intro'
      preLoaderRoute: typeof DocsIspIntroRouteImport
      parentRoute: typeof DocsIspRoute
    }
    '/docs/isp/first-request': {
      id: '/docs/isp/first-request'
      path: '/first-request'
      fullPath: '/docs/isp/first-request'
      preLoaderRoute: typeof DocsIspFirstRequestRouteImport
      parentRoute: typeof DocsIspRoute
    }
    '/docs/isp/faq': {
      id: '/docs/isp/faq'
      path: '/faq'
      fullPath: '/docs/isp/faq'
      preLoaderRoute: typeof DocsIspFaqRouteImport
      parentRoute: typeof DocsIspRoute
    }
    '/docs/isp/configuration': {
      id: '/docs/isp/configuration'
      path: '/configuration'
      fullPath: '/docs/isp/configuration'
      preLoaderRoute: typeof DocsIspConfigurationRouteImport
      parentRoute: typeof DocsIspRoute
    }
    '/docs/fingerprint-browser/ziniao': {
      id: '/docs/fingerprint-browser/ziniao'
      path: '/ziniao'
      fullPath: '/docs/fingerprint-browser/ziniao'
      preLoaderRoute: typeof DocsFingerprintBrowserZiniaoRouteImport
      parentRoute: typeof DocsFingerprintBrowserRoute
    }
    '/docs/fingerprint-browser/linkensphere': {
      id: '/docs/fingerprint-browser/linkensphere'
      path: '/linkensphere'
      fullPath: '/docs/fingerprint-browser/linkensphere'
      preLoaderRoute: typeof DocsFingerprintBrowserLinkensphereRouteImport
      parentRoute: typeof DocsFingerprintBrowserRoute
    }
    '/docs/fingerprint-browser/ixbrowser': {
      id: '/docs/fingerprint-browser/ixbrowser'
      path: '/ixbrowser'
      fullPath: '/docs/fingerprint-browser/ixbrowser'
      preLoaderRoute: typeof DocsFingerprintBrowserIxbrowserRouteImport
      parentRoute: typeof DocsFingerprintBrowserRoute
    }
    '/docs/fingerprint-browser/hubstudio': {
      id: '/docs/fingerprint-browser/hubstudio'
      path: '/hubstudio'
      fullPath: '/docs/fingerprint-browser/hubstudio'
      preLoaderRoute: typeof DocsFingerprintBrowserHubstudioRouteImport
      parentRoute: typeof DocsFingerprintBrowserRoute
    }
    '/docs/fingerprint-browser/bitbrowser': {
      id: '/docs/fingerprint-browser/bitbrowser'
      path: '/bitbrowser'
      fullPath: '/docs/fingerprint-browser/bitbrowser'
      preLoaderRoute: typeof DocsFingerprintBrowserBitbrowserRouteImport
      parentRoute: typeof DocsFingerprintBrowserRoute
    }
    '/docs/fingerprint-browser/adspower': {
      id: '/docs/fingerprint-browser/adspower'
      path: '/adspower'
      fullPath: '/docs/fingerprint-browser/adspower'
      preLoaderRoute: typeof DocsFingerprintBrowserAdspowerRouteImport
      parentRoute: typeof DocsFingerprintBrowserRoute
    }
    '/docs/fingerprint-browser/VMLogin': {
      id: '/docs/fingerprint-browser/VMLogin'
      path: '/VMLogin'
      fullPath: '/docs/fingerprint-browser/VMLogin'
      preLoaderRoute: typeof DocsFingerprintBrowserVMLoginRouteImport
      parentRoute: typeof DocsFingerprintBrowserRoute
    }
    '/docs/fingerprint-browser/MuLogin': {
      id: '/docs/fingerprint-browser/MuLogin'
      path: '/MuLogin'
      fullPath: '/docs/fingerprint-browser/MuLogin'
      preLoaderRoute: typeof DocsFingerprintBrowserMuLoginRouteImport
      parentRoute: typeof DocsFingerprintBrowserRoute
    }
    '/docs/fingerprint-browser/MoreLogin': {
      id: '/docs/fingerprint-browser/MoreLogin'
      path: '/MoreLogin'
      fullPath: '/docs/fingerprint-browser/MoreLogin'
      preLoaderRoute: typeof DocsFingerprintBrowserMoreLoginRouteImport
      parentRoute: typeof DocsFingerprintBrowserRoute
    }
    '/docs/fingerprint-browser/GoLogin': {
      id: '/docs/fingerprint-browser/GoLogin'
      path: '/GoLogin'
      fullPath: '/docs/fingerprint-browser/GoLogin'
      preLoaderRoute: typeof DocsFingerprintBrowserGoLoginRouteImport
      parentRoute: typeof DocsFingerprintBrowserRoute
    }
    '/docs/extension/SwitchyOmega': {
      id: '/docs/extension/SwitchyOmega'
      path: '/SwitchyOmega'
      fullPath: '/docs/extension/SwitchyOmega'
      preLoaderRoute: typeof DocsExtensionSwitchyOmegaRouteImport
      parentRoute: typeof DocsExtensionRoute
    }
    '/docs/extension/Postern': {
      id: '/docs/extension/Postern'
      path: '/Postern'
      fullPath: '/docs/extension/Postern'
      preLoaderRoute: typeof DocsExtensionPosternRouteImport
      parentRoute: typeof DocsExtensionRoute
    }
    '/docs/extension/FoxyProxy': {
      id: '/docs/extension/FoxyProxy'
      path: '/FoxyProxy'
      fullPath: '/docs/extension/FoxyProxy'
      preLoaderRoute: typeof DocsExtensionFoxyProxyRouteImport
      parentRoute: typeof DocsExtensionRoute
    }
    '/docs/chain-proxy/v2rayn': {
      id: '/docs/chain-proxy/v2rayn'
      path: '/v2rayn'
      fullPath: '/docs/chain-proxy/v2rayn'
      preLoaderRoute: typeof DocsChainProxyV2raynRouteImport
      parentRoute: typeof DocsChainProxyRoute
    }
    '/docs/chain-proxy/proxifier': {
      id: '/docs/chain-proxy/proxifier'
      path: '/proxifier'
      fullPath: '/docs/chain-proxy/proxifier'
      preLoaderRoute: typeof DocsChainProxyProxifierRouteImport
      parentRoute: typeof DocsChainProxyRoute
    }
    '/docs/chain-proxy/clash-verge': {
      id: '/docs/chain-proxy/clash-verge'
      path: '/clash-verge'
      fullPath: '/docs/chain-proxy/clash-verge'
      preLoaderRoute: typeof DocsChainProxyClashVergeRouteImport
      parentRoute: typeof DocsChainProxyRoute
    }
  }
}

interface DocsChainProxyRouteChildren {
  DocsChainProxyClashVergeRoute: typeof DocsChainProxyClashVergeRoute
  DocsChainProxyProxifierRoute: typeof DocsChainProxyProxifierRoute
  DocsChainProxyV2raynRoute: typeof DocsChainProxyV2raynRoute
}

const DocsChainProxyRouteChildren: DocsChainProxyRouteChildren = {
  DocsChainProxyClashVergeRoute: DocsChainProxyClashVergeRoute,
  DocsChainProxyProxifierRoute: DocsChainProxyProxifierRoute,
  DocsChainProxyV2raynRoute: DocsChainProxyV2raynRoute,
}

const DocsChainProxyRouteWithChildren = DocsChainProxyRoute._addFileChildren(
  DocsChainProxyRouteChildren,
)

interface DocsExtensionRouteChildren {
  DocsExtensionFoxyProxyRoute: typeof DocsExtensionFoxyProxyRoute
  DocsExtensionPosternRoute: typeof DocsExtensionPosternRoute
  DocsExtensionSwitchyOmegaRoute: typeof DocsExtensionSwitchyOmegaRoute
}

const DocsExtensionRouteChildren: DocsExtensionRouteChildren = {
  DocsExtensionFoxyProxyRoute: DocsExtensionFoxyProxyRoute,
  DocsExtensionPosternRoute: DocsExtensionPosternRoute,
  DocsExtensionSwitchyOmegaRoute: DocsExtensionSwitchyOmegaRoute,
}

const DocsExtensionRouteWithChildren = DocsExtensionRoute._addFileChildren(
  DocsExtensionRouteChildren,
)

interface DocsFingerprintBrowserRouteChildren {
  DocsFingerprintBrowserGoLoginRoute: typeof DocsFingerprintBrowserGoLoginRoute
  DocsFingerprintBrowserMoreLoginRoute: typeof DocsFingerprintBrowserMoreLoginRoute
  DocsFingerprintBrowserMuLoginRoute: typeof DocsFingerprintBrowserMuLoginRoute
  DocsFingerprintBrowserVMLoginRoute: typeof DocsFingerprintBrowserVMLoginRoute
  DocsFingerprintBrowserAdspowerRoute: typeof DocsFingerprintBrowserAdspowerRoute
  DocsFingerprintBrowserBitbrowserRoute: typeof DocsFingerprintBrowserBitbrowserRoute
  DocsFingerprintBrowserHubstudioRoute: typeof DocsFingerprintBrowserHubstudioRoute
  DocsFingerprintBrowserIxbrowserRoute: typeof DocsFingerprintBrowserIxbrowserRoute
  DocsFingerprintBrowserLinkensphereRoute: typeof DocsFingerprintBrowserLinkensphereRoute
  DocsFingerprintBrowserZiniaoRoute: typeof DocsFingerprintBrowserZiniaoRoute
}

const DocsFingerprintBrowserRouteChildren: DocsFingerprintBrowserRouteChildren =
  {
    DocsFingerprintBrowserGoLoginRoute: DocsFingerprintBrowserGoLoginRoute,
    DocsFingerprintBrowserMoreLoginRoute: DocsFingerprintBrowserMoreLoginRoute,
    DocsFingerprintBrowserMuLoginRoute: DocsFingerprintBrowserMuLoginRoute,
    DocsFingerprintBrowserVMLoginRoute: DocsFingerprintBrowserVMLoginRoute,
    DocsFingerprintBrowserAdspowerRoute: DocsFingerprintBrowserAdspowerRoute,
    DocsFingerprintBrowserBitbrowserRoute:
      DocsFingerprintBrowserBitbrowserRoute,
    DocsFingerprintBrowserHubstudioRoute: DocsFingerprintBrowserHubstudioRoute,
    DocsFingerprintBrowserIxbrowserRoute: DocsFingerprintBrowserIxbrowserRoute,
    DocsFingerprintBrowserLinkensphereRoute:
      DocsFingerprintBrowserLinkensphereRoute,
    DocsFingerprintBrowserZiniaoRoute: DocsFingerprintBrowserZiniaoRoute,
  }

const DocsFingerprintBrowserRouteWithChildren =
  DocsFingerprintBrowserRoute._addFileChildren(
    DocsFingerprintBrowserRouteChildren,
  )

interface DocsIspRouteChildren {
  DocsIspConfigurationRoute: typeof DocsIspConfigurationRoute
  DocsIspFaqRoute: typeof DocsIspFaqRoute
  DocsIspFirstRequestRoute: typeof DocsIspFirstRequestRoute
  DocsIspIntroRoute: typeof DocsIspIntroRoute
  DocsIspQuickstartRoute: typeof DocsIspQuickstartRoute
}

const DocsIspRouteChildren: DocsIspRouteChildren = {
  DocsIspConfigurationRoute: DocsIspConfigurationRoute,
  DocsIspFaqRoute: DocsIspFaqRoute,
  DocsIspFirstRequestRoute: DocsIspFirstRequestRoute,
  DocsIspIntroRoute: DocsIspIntroRoute,
  DocsIspQuickstartRoute: DocsIspQuickstartRoute,
}

const DocsIspRouteWithChildren =
  DocsIspRoute._addFileChildren(DocsIspRouteChildren)

interface DocsMobileRouteChildren {
  DocsMobileAndroidRoute: typeof DocsMobileAndroidRoute
  DocsMobileIosRoute: typeof DocsMobileIosRoute
}

const DocsMobileRouteChildren: DocsMobileRouteChildren = {
  DocsMobileAndroidRoute: DocsMobileAndroidRoute,
  DocsMobileIosRoute: DocsMobileIosRoute,
}

const DocsMobileRouteWithChildren = DocsMobileRoute._addFileChildren(
  DocsMobileRouteChildren,
)

interface DocsResidentialRouteChildren {
  DocsResidentialConfigurationRoute: typeof DocsResidentialConfigurationRoute
  DocsResidentialFaqRoute: typeof DocsResidentialFaqRoute
  DocsResidentialFirstRequestRoute: typeof DocsResidentialFirstRequestRoute
  DocsResidentialIntroRoute: typeof DocsResidentialIntroRoute
  DocsResidentialQuickstartRoute: typeof DocsResidentialQuickstartRoute
}

const DocsResidentialRouteChildren: DocsResidentialRouteChildren = {
  DocsResidentialConfigurationRoute: DocsResidentialConfigurationRoute,
  DocsResidentialFaqRoute: DocsResidentialFaqRoute,
  DocsResidentialFirstRequestRoute: DocsResidentialFirstRequestRoute,
  DocsResidentialIntroRoute: DocsResidentialIntroRoute,
  DocsResidentialQuickstartRoute: DocsResidentialQuickstartRoute,
}

const DocsResidentialRouteWithChildren = DocsResidentialRoute._addFileChildren(
  DocsResidentialRouteChildren,
)

interface DocsStaticDatacenterRouteChildren {
  DocsStaticDatacenterConfigurationRoute: typeof DocsStaticDatacenterConfigurationRoute
  DocsStaticDatacenterFaqRoute: typeof DocsStaticDatacenterFaqRoute
  DocsStaticDatacenterFirstRequestRoute: typeof DocsStaticDatacenterFirstRequestRoute
  DocsStaticDatacenterIntroRoute: typeof DocsStaticDatacenterIntroRoute
  DocsStaticDatacenterQuickstartRoute: typeof DocsStaticDatacenterQuickstartRoute
}

const DocsStaticDatacenterRouteChildren: DocsStaticDatacenterRouteChildren = {
  DocsStaticDatacenterConfigurationRoute:
    DocsStaticDatacenterConfigurationRoute,
  DocsStaticDatacenterFaqRoute: DocsStaticDatacenterFaqRoute,
  DocsStaticDatacenterFirstRequestRoute: DocsStaticDatacenterFirstRequestRoute,
  DocsStaticDatacenterIntroRoute: DocsStaticDatacenterIntroRoute,
  DocsStaticDatacenterQuickstartRoute: DocsStaticDatacenterQuickstartRoute,
}

const DocsStaticDatacenterRouteWithChildren =
  DocsStaticDatacenterRoute._addFileChildren(DocsStaticDatacenterRouteChildren)

interface DocsStaticResidentialRouteChildren {
  DocsStaticResidentialConfigurationRoute: typeof DocsStaticResidentialConfigurationRoute
  DocsStaticResidentialFaqRoute: typeof DocsStaticResidentialFaqRoute
  DocsStaticResidentialFirstRequestRoute: typeof DocsStaticResidentialFirstRequestRoute
  DocsStaticResidentialIntroRoute: typeof DocsStaticResidentialIntroRoute
  DocsStaticResidentialQuickstartRoute: typeof DocsStaticResidentialQuickstartRoute
}

const DocsStaticResidentialRouteChildren: DocsStaticResidentialRouteChildren = {
  DocsStaticResidentialConfigurationRoute:
    DocsStaticResidentialConfigurationRoute,
  DocsStaticResidentialFaqRoute: DocsStaticResidentialFaqRoute,
  DocsStaticResidentialFirstRequestRoute:
    DocsStaticResidentialFirstRequestRoute,
  DocsStaticResidentialIntroRoute: DocsStaticResidentialIntroRoute,
  DocsStaticResidentialQuickstartRoute: DocsStaticResidentialQuickstartRoute,
}

const DocsStaticResidentialRouteWithChildren =
  DocsStaticResidentialRoute._addFileChildren(
    DocsStaticResidentialRouteChildren,
  )

interface DocsUnlimitedResidentialRouteChildren {
  DocsUnlimitedResidentialConfigurationRoute: typeof DocsUnlimitedResidentialConfigurationRoute
  DocsUnlimitedResidentialFaqRoute: typeof DocsUnlimitedResidentialFaqRoute
  DocsUnlimitedResidentialFirstRequestRoute: typeof DocsUnlimitedResidentialFirstRequestRoute
  DocsUnlimitedResidentialIntroRoute: typeof DocsUnlimitedResidentialIntroRoute
  DocsUnlimitedResidentialQuickstartRoute: typeof DocsUnlimitedResidentialQuickstartRoute
}

const DocsUnlimitedResidentialRouteChildren: DocsUnlimitedResidentialRouteChildren =
  {
    DocsUnlimitedResidentialConfigurationRoute:
      DocsUnlimitedResidentialConfigurationRoute,
    DocsUnlimitedResidentialFaqRoute: DocsUnlimitedResidentialFaqRoute,
    DocsUnlimitedResidentialFirstRequestRoute:
      DocsUnlimitedResidentialFirstRequestRoute,
    DocsUnlimitedResidentialIntroRoute: DocsUnlimitedResidentialIntroRoute,
    DocsUnlimitedResidentialQuickstartRoute:
      DocsUnlimitedResidentialQuickstartRoute,
  }

const DocsUnlimitedResidentialRouteWithChildren =
  DocsUnlimitedResidentialRoute._addFileChildren(
    DocsUnlimitedResidentialRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsChainProxyRoute: DocsChainProxyRouteWithChildren,
  DocsContactRoute: DocsContactRoute,
  DocsExtensionRoute: DocsExtensionRouteWithChildren,
  DocsFingerprintBrowserRoute: DocsFingerprintBrowserRouteWithChildren,
  DocsIntroRoute: DocsIntroRoute,
  DocsIspRoute: DocsIspRouteWithChildren,
  DocsMobileRoute: DocsMobileRouteWithChildren,
  DocsResidentialRoute: DocsResidentialRouteWithChildren,
  DocsStaticDatacenterRoute: DocsStaticDatacenterRouteWithChildren,
  DocsStaticResidentialRoute: DocsStaticResidentialRouteWithChildren,
  DocsUnlimitedResidentialRoute: DocsUnlimitedResidentialRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
